# Generated by Django 4.0.4 on 2022-05-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_daterecord_unique_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='planstart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
