# Generated by Django 4.0.4 on 2022-05-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_alter_habit_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('name', 'planstart'), name='unique_habit'),
        ),
    ]
