# Generated by Django 4.0.4 on 2022-05-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0008_habit_unique_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='daterecord',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_records', to='habit.habit'),
        ),
    ]
